### ISSUE TITLE
update(val, n) doesn't update max and min vals so getValN won't work

### ISSUE THREAD

**Issue by robin-price** [turowskipaul/ofxDataStream#1]
the code to update the min and max vals never gets called by the regular update call.

**Comment by turowskipaul** [comment]
Thanks for your comment. I haven't updated this in a long time and don't plan to as I don't use OpenFrameworks at all anymore, so I'm going to archive it. Hopefully at least some of it might be useful to others and fixed/expanded upon. Cheers.
